version: '3.8'
services:

  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareIt-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090


  server:
    build: server
    image: shareit-server
    container_name: shareIt-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iamroot


  db:
    image: postgres:15.3-alpine
    container_name: shareIt-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot











